services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 3000
      DATABASE_URL: postgres://admin:admin@postgres:5432/foreign_aid
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: foreign-aid

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: foreign_aid

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin  -d foreign_aid"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
